# Generated by Django 3.0.8 on 2020-08-19 09:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0009_auto_20200816_1455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 19, 9, 51, 8, 198996, tzinfo=utc)),
        ),
    ]
