# Generated by Django 3.0.8 on 2020-08-23 11:40

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0012_auto_20200822_1317'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 23, 11, 40, 19, 534759, tzinfo=utc)),
        ),
    ]
