# Generated by Django 3.0.8 on 2020-09-05 15:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0022_auto_20200827_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 5, 15, 18, 21, 440461, tzinfo=utc)),
        ),
    ]
