# Generated by Django 3.0.8 on 2020-09-05 16:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0023_auto_20200905_1818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 5, 16, 12, 12, 593622, tzinfo=utc)),
        ),
    ]
