# Generated by Django 3.0.8 on 2020-09-05 16:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0024_auto_20200905_1912'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 5, 16, 22, 53, 208474, tzinfo=utc)),
        ),
    ]
