# Generated by Django 3.0.8 on 2020-09-07 07:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0025_auto_20200905_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 7, 7, 1, 49, 630966, tzinfo=utc)),
        ),
    ]
