# Generated by Django 3.0.8 on 2020-09-07 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0026_auto_20200907_1001'),
        ('News', '0023_merge_20200827_2045'),
    ]

    operations = [
    ]
