# Generated by Django 3.0.8 on 2020-09-07 09:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('News', '0027_merge_20200907_1249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 7, 9, 50, 5, 777291, tzinfo=utc)),
        ),
    ]
