# Generated by Django 3.0.8 on 2020-09-05 16:12

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Segment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='segment',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 5, 16, 12, 12, 596487, tzinfo=utc)),
        ),
    ]
