# Generated by Django 3.0.8 on 2020-09-05 16:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Segment', '0002_segment_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 5, 16, 22, 53, 212814, tzinfo=utc)),
        ),
    ]
