# Generated by Django 3.0.8 on 2020-09-07 07:01

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Segment', '0003_auto_20200905_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 7, 7, 1, 49, 635063, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='segment',
            name='segment',
            field=models.CharField(choices=[('TU', 'שירותים'), ('JU', 'חדר זבל'), ('CO', 'מגרש'), ('TR', 'טריבונות'), ('GT', 'מרצפות אפורות מחוץ לחדרים'), ('TT', 'מרצפות מחוץ לשירותים'), ('GR', 'חצץ'), ('BI', 'אופניים'), ('HA', 'חדר חמישיוט'), ('TC', 'החלפת פחים'), ('SR', 'חדר שכב״ג'), ('HR', 'חדר חיים'), ('ZR', 'חדר צמיד'), ('AU', 'אולם'), ('YT', 'מרצפות צהובות'), ('ES', 'כניסה לשבט (מבפנים ומבחוץ)'), ('PI', 'מערום'), ('WR', 'חדר מחסן'), ('KR', 'חדר קיוסק'), ('TG', 'חדר תחזוקה'), ('MR', 'חדר מרכזים')], default='CO', max_length=2),
        ),
    ]
