# Generated by Django 3.0.8 on 2020-09-07 09:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Segment', '0004_auto_20200907_1001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='segment',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 9, 7, 9, 50, 5, 780483, tzinfo=utc)),
        ),
    ]
