# Generated by Django 3.0.8 on 2020-08-11 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('Approved', models.BooleanField()),
                ('Active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='Torder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('Approved', models.BooleanField()),
                ('Active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.User')),
            ],
        ),
        migrations.CreateModel(
            name='Aorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('area', models.CharField(choices=[('AU', 'אולם'), ('CO', 'מגרש'), ('BY', 'מערום'), ('WO', 'חורשה')], default='CO', max_length=2)),
                ('date', models.DateTimeField()),
                ('Approved', models.BooleanField()),
                ('Active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='Accounts.User')),
            ],
        ),
    ]
