# Generated by Django 3.0.8 on 2020-08-12 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0003_auto_20200811_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aorder',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='torder',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='worder',
            name='date',
            field=models.DateField(),
        ),
        migrations.DeleteModel(
            name='Text',
        ),
    ]
