# Generated by Django 3.0.8 on 2020-08-12 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0005_auto_20200812_1533'),
    ]

    operations = [
        migrations.AlterField(
            model_name='worder',
            name='date',
            field=models.DateField(),
        ),
    ]
