# Generated by Django 3.0.8 on 2020-08-19 09:51

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0018_auto_20200816_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='worder',
            name='collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aorder',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 19, 9, 51, 8, 194746, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='torder',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 19, 9, 51, 8, 194296, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='worder',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 19, 9, 51, 8, 193738, tzinfo=utc)),
        ),
    ]
