# Generated by Django 3.0.8 on 2020-08-25 12:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0022_auto_20200825_1218'),
    ]

    operations = [
        migrations.AddField(
            model_name='worder',
            name='deleted_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='aorder',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 25, 12, 22, 9, 249870, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='torder',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 25, 12, 22, 9, 249279, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='worder',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 25, 12, 22, 9, 248823, tzinfo=utc)),
        ),
    ]
