# Generated by Django 3.0.8 on 2020-08-25 12:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0023_auto_20200825_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aorder',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 25, 12, 35, 13, 280896, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='torder',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 25, 12, 35, 13, 280301, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='worder',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 25, 12, 35, 13, 279819, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='worder',
            name='deleted_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
