# Generated by Django 3.0.8 on 2020-08-27 10:33

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0030_auto_20200827_0318'),
    ]

    operations = [
        migrations.AddField(
            model_name='torder',
            name='collected',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='aorder',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 27, 10, 33, 46, 943283, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='torder',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 27, 10, 33, 46, 942672, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='worder',
            name='date',
            field=models.DateField(default=datetime.datetime(2020, 8, 27, 10, 33, 46, 942132, tzinfo=utc)),
        ),
    ]
