# Generated by Django 3.0.8 on 2020-08-27 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0022_auto_20200823_1140'),
        ('Orders', '0031_auto_20200827_1333'),
    ]

    operations = [
    ]
