# Generated by Django 3.0.8 on 2020-09-07 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Orders', '0032_merge_20200827_2045'),
        ('Orders', '0035_auto_20200907_1001'),
    ]

    operations = [
    ]
